# Generated by Django 4.2.7 on 2023-11-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video_collection", "0002_video_videos_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="video", name="videos_id",),
    ]
